# Generated by Django 4.2.11 on 2024-03-14 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=140)),
                ('content', models.TextField(max_length=2097152, verbose_name='')),
            ],
        ),
    ]
